/*
 * WF_Table.h
 *
 *  Created on: Dec 25, 2018
 *      Author: user
 */

#ifndef WF_TABLE_H_
#define WF_TABLE_H_

const uint32_t WFPalette[] = {
		LCD_COLOR_DARKBLUE,
		LCD_COLOR_BLUE,
		LCD_COLOR_LIGHTBLUE,
		LCD_COLOR_DARKGREEN,
		LCD_COLOR_GREEN,
		LCD_COLOR_LIGHTGREEN,
		LCD_COLOR_DARKRED,
		LCD_COLOR_RED,
		LCD_COLOR_LIGHTRED,
		LCD_COLOR_ORANGE,
		LCD_COLOR_DARKYELLOW,
		LCD_COLOR_YELLOW,
		LCD_COLOR_LIGHTYELLOW,
		LCD_COLOR_WHITE,
		LCD_COLOR_GRAY
};

#endif /* WF_TABLE_H_ */

